# Author: Konstantin M.J. Winkel, M.Sc.

"""
This file contains type definitions for types needed to interact with the
json files generated by pylints json2 setting.
"""

import logging

from dataclasses import dataclass
from enum import Enum

logger = logging.getLogger(__name__)

class PylintConfidence(Enum):
    """This Enum defines values for the Pylint Confidence levels"""

    UNDEFINED = 0
    INFERENCE_FAILURE = 1
    INFERENCE = 2
    CONTROL_FLOW = 3
    HIGH = 4

def pylint_confidence_from_string(string: str) -> PylintConfidence:
    """This method creates a PylintConfidence value from a string"""

    conversion_dict = { "UNDEFINED":         PylintConfidence.UNDEFINED,
                        "INFERENCE_FAILURE": PylintConfidence.INFERENCE_FAILURE,
                        "INFERENCE":         PylintConfidence.INFERENCE,
                        "CONTROL_FLOW":      PylintConfidence.CONTROL_FLOW,
                        "HIGH":              PylintConfidence.HIGH
                        }

    if string not in conversion_dict:
        logger.warning("Unkown Pylint Condifence string %s, defaulting to UNDEFINED", string)
        return PylintConfidence.UNDEFINED

    return conversion_dict[string]

@dataclass
class PylintMessage:
    """This Dataclass includes all fields emitted by the pylint json2 setting"""

    type: str
    symbol: str
    message: str
    message_id: str
    confidence: PylintConfidence
    module: str
    obj: str
    line: int
    column: int
    end_line: int
    end_column: int
    path: str
    absolute_path: str

PYLINT_MESSAGE_KEYS = ["type","symbol","message","messageId","confidence","module","obj","line",
                       "column","endLine","endColumn","path","absolutePath"]
